In [6]:
import sklearn
import numpy as np
import scipy
import math

In [2]:
sklearn.__version__

'0.19.1'

In [21]:
def fact(x):
    res = 1;
    for i in range(1, x + 1):
        res *= i
    return res

def cnk(n, k):
    return fact(n) / (fact(k) * fact(n - k))

In [26]:
def get(n):
    sign = 1
    ans = 0
    for i in range(1, n + 1):
        if i % 2 == 0:
            ans += cnk(n, i) * sign
            sign *= -1
    return ans

In [33]:
#for i in range(1, 10):
#    print i, get(i)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
C = np.array([[2, 1],[3, 2]])

In [22]:
invC = np.linalg.inv(C)
invC

array([[ 2., -1.],
       [-3.,  2.]])

In [24]:
v = np.dot(invC, B)

In [25]:
ans = np.dot(v, inv)

In [26]:
ans

array([[ 24.,  13.],
       [-34., -18.]])

In [27]:
np.dot(np.dot(C, ans), A)

array([[-2.,  4.],
       [ 3., -1.]])